### PR TITLE
Swift 4.0.2 / Xcode 9.1

### PR DESCRIPTION
**Pull request by NachoSoto**

### CODE REVIEW

**Comment by NachoSoto** [comment]
Waiting on https://github.com/travis-ci/travis-ci/issues/8700...

**Comment by cotsog** [comment]
The newest Xcode 9.1 (build number 9B55) should now be available for real. Could you try to restart your build?

**Comment by eneko** [comment]
@NachoSoto how are you importing the frameworks on your project? Maybe add a `carthage bootstrap` task to your Travis CI configuration, so dependencies are rebuilt if they don't match the binary version.

While Travis should fix their stuff, depending on the environment matching the Swift version your binaries were built with does not sound like a good idea.

**Comment by eneko** [comment]
Here is an example of our output (our builds pass fine):
```
=== EXECUTE: carthage bootstrap --cache-builds ===
*** Downloading Conduit.framework binary at "Release 0.7.0"
*** Skipped installing Conduit.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.1 (swiftlang-900.0.66 clang-900.0.37)."
*** Checking out Conduit at "0.7.0"
*** Cloning Conduit
*** xcodebuild output can be found in /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/carthage-xcodebuild.84k0dm.log
*** Valid cache found for Conduit, skipping build
```

So, we couldn't use the binary because of the version mismatch, but Carthage can clone and build the sources. In this case, a cache was found, so no build was needed.

**Comment by NachoSoto** [comment]
> depending on the environment matching the Swift version your binaries were built with does not sound like a good idea.

Why not? I'm updating this to work with Xcode 9.1, so I want to build on a CI with the same version.

**Comment by eneko** [comment]
For many reasons. The most important one that you lose all chances for Swift version compatibility.

Swift 4 is compatible with Swift 3.2 (you can mix 3.2 modules with 4 in the same application). Same goes for 4.0, 4.0.1, etc.  But this only applies when building from sources. Unfortunately, it does not work with binaries. 

For example, by using binaries only, you would find incompatibilities between Xcode 9 beta 2 and beta 5, both of them with different versions of Swift 4.0. 

You should update your build scripts to always run `carthage bootstrap` first.

**Comment by NachoSoto** [comment]
Are you using this framework? If so I'll be happy to improve support for other Swift versions. As it is right now, this is just a personal project.

**Pull request merged**
